# Generated by Django 3.0.4 on 2020-03-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('family', '0003_auto_20200322_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('U8', 'Superbaby'), ('U10', 'Mladší predžiaci'), ('U12', 'Starší predžiaci'), ('U14', 'Mladší žiaci'), ('U16', 'Starší žiaci'), ('U18', 'Juniory'), ('U21', 'Dospelý')], max_length=3)),
                ('year_from', models.DateField()),
                ('year_until', models.DateField()),
                ('children', models.ManyToManyField(blank=True, to='family.Child')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Ski Training', 'Ski Training'), ('SKi Race', 'Ski Race'), ('SKi Camp', 'Ski Camp')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('category', models.ManyToManyField(to='events.Category')),
                ('participants', models.ManyToManyField(blank=True, to='family.Child')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_events.event_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkiTraining',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
                ('skis_type', models.CharField(choices=[('GS', 'Giant Slalom'), ('SL', 'Slalom'), ('AL', 'All')], default='AL', max_length=2)),
                ('number_of_turns', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('events.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season'),
        ),
        migrations.AddField(
            model_name='category',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('session', 'name')},
        ),
    ]
