# Generated by Django 3.0.4 on 2020-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200324_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='skitraining',
            name='extra_field_for_ski_training',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skitraining',
            name='extra_field_for_ski_training1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skitraining',
            name='extra_field_for_ski_training2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skitraining',
            name='extra_field_for_ski_training3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
