# Generated by Django 3.0.5 on 2020-04-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200405_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='id',
            field=models.AutoField(auto_created=True, default='tes', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
