# Generated by Django 3.0.4 on 2020-03-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200330_1950'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'ski_slope')},
        ),
    ]
