# Generated by Django 3.0.5 on 2020-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200405_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='id',
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
