# Generated by Django 3.0.4 on 2020-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200325_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Default Title For Event', max_length=100),
        ),
    ]
