# Generated by Django 3.0.4 on 2020-03-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20200322_1358'),
        ('events', '0006_auto_20200325_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='members',
            field=models.ManyToManyField(to='family.Child'),
        ),
    ]
