# Generated by Django 3.0.4 on 2020-03-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_child_categories'),
        ('events', '0007_auto_20200326_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='members',
            field=models.ManyToManyField(blank=True, to='family.Child'),
        ),
    ]
