# Generated by Django 3.0.4 on 2020-03-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200324_0921'),
        ('events', '0008_auto_20200326_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
