version: "3.8"

services:
  backend:
    volumes:
      - ./backend:/app
    entrypoint: /entrypoint.sh
    command: /gunicorn.sh

  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data # persist data even if container shuts down

  nginx:
    expose:
      - 80
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}

# TODO: Which folder to backup in volumes
  backups:
    image: prodrigestivill/postgres-backup-local
    restart: on-failure
    environment:
      - POSTGRES_PORT=${DB_PORT}
    depends_on:
      - postgres
    volumes:
      - /tmp/backups/:/backups/
      - /var/lib/postgresql/data:/backups/
      - postgres_data:/backups/postgres_data

volumes:
    postgres_data: {}

networks:
  default:
    name: nginx-proxy
    external: true


#  postgres:
#    image: postgres
#    expose:
#      - ${DB_PORT} # Publishes port to other containers but NOT to host machine
#    command: -p ${DB_PORT}
#    env_file:  ${ENV_FILE:-.env}
#
#  nginx:
#    image: "ghcr.io/dominikbullo/sportagenda_nginx:${IMAGE_VERSION}"
#    depends_on:
#      - backend
#    env_file: ${ENV_FILE:-.env}
