# Used on to download images and deploy site
version: "3"

volumes:
    postgres_data_stage: {}

services:
  backend:
    volumes:
      - ./backend:/app
    entrypoint: /entrypoint.sh
    command: /gunicorn.sh
    restart: on-failure

  postgres:
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data # persist data even if container shuts down

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
