version: "3.8"

services:
  postgres:
    ports:
      - ${DB_PORT}:${DB_PORT}

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file: .env

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    logging:
      driver: none
