version: "3"

services:
  backend:
    image: ghcr.io/dominikbullo/sportagenda_backend:${IMAGE_VERSION}
    entrypoint: /entrypoint.sh
    depends_on:
      - postgres

  postgres:
    image: postgres

  nginx:
    image: ghcr.io/dominikbullo/sportagenda_nginx:${IMAGE_VERSION}
    depends_on:
      - backend
    expose:
      - 80


