# Base file for docker-compose
# If you run this file without docker-compose.override.yml file, nothing happened, you need to it with some another file
# If you run this file with docker-compose.override.yml file, it will be automatically accepted as another file
# RES: https://docs.docker.com/compose/extends/
version: "3"

services:
  backend:
    image: "ghcr.io/dominikbullo/sportagenda_backend:${IMAGE_VERSION}"
    depends_on:
      - postgres
    restart: on-failure
    env_file: .env

  postgres:
    image: postgres
    expose:
      - ${DB_PORT} # Publishes port to other containers but NOT to host machine
    command: -p ${DB_PORT}
    env_file: .env

  nginx:
    image: "ghcr.io/dominikbullo/sportagenda_nginx:${IMAGE_VERSION}"
    depends_on:
      - backend
    env_file: .env
