version: "3"

services:
  backend:
    image: ghcr.io/dominikbullo/sportagenda_backend:${IMAGE_VERSION}
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres
    env_file: .env

  nginx:
    image: ghcr.io/dominikbullo/sportagenda_nginx:${IMAGE_VERSION}
    depends_on:
      - backend
    expose:
      - 80
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}


networks:
  default:
    external:
      name: nginx-proxy
