# Used on to download images and deploy site
version: "3"

volumes:
    postgres_data: {}

services:
  backend:
    image: ghcr.io/dominikbullo/sportagenda_backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    env_file: .env
    restart: on-failure

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    image: ghcr.io/dominikbullo/sportagenda_nginx
    expose:
      - 80
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}



  backups:
    image: prodrigestivill/postgres-backup-local
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - /tmp/backups/:/backups/


networks:
  default:
    external:
      name: nginx-proxy
