version: "3.8"

services:
  backend:
    build:
      context: ./backend
    command: bash -c "poetry install && poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    env_file: ${ENV_FILE:-.env}
    restart: on-failure
    volumes:
      - ./backend:/app/backend

  postgres:
    image: postgres
    expose:
      - 1234
    command: -p 1234
    env_file: ${ENV_FILE:-.env}
    volumes:
      - sportagenda_data:/var/lib/postgresql/data/

  frontend:
    image: node:14-alpine
    command: npm run serve
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend/media/:/media/
      - ./backend/static/:/static/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    env_file: ${ENV_FILE:-.env}

volumes:
  sportagenda_data:
  pgadmin_data:
