version: "3"

services:
  backend:
    image: ghcr.io/dominikbullo/sportagenda_backend:${IMAGE_VERSION}
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres
    env_file: .env

  nginx:
    image: ghcr.io/dominikbullo/sportagenda_nginx:${IMAGE_VERSION}
    depends_on:
      - backend
    expose:
      - 80
    env_file: .env
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}


