# Used for creating image, pushing to registry which will be deployed
version: "3"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    expose:
      - 80
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
