version: '3.3'

services:
  backend:
    build:
      context: ./backend
    image: ghcr.io/dominikbullo/sportagenda_backend
    volumes:
      - ./backend:/app
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: ghcr.io/dominikbullo/sportagenda_nginx
    expose:
      - 80
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
