# Used for creating image, pushing to registry which will be deployed
version: "3"

services:
  backend:
    build:
      context: ./backend
    env_file: .env.dev

  postgres:
    env_file: .env.dev

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    env_file: .env.dev
