# Used on to download images and deploy site
version: "3"


services:
  backend:
    image: "ghcr.io/dominikbullo/sportagenda_backend:${IMAGE_VERSION}"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    entrypoint: /entrypoint.sh
    command: /gunicorn.sh
    restart: on-failure
    env_file: .env

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data # persist data even if container shuts down
    env_file: .env

  nginx:
    image: "ghcr.io/dominikbullo/sportagenda_nginx:${IMAGE_VERSION}"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
    env_file: .env
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}

volumes:
    postgres_data: {}

#networks:
#  default:
#    external:
#      name: nginx-proxy
