# Generated by Django 3.1.2 on 2020-10-28 18:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_auto_20201028_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="average_time",
            field=models.DurationField(default=datetime.timedelta(seconds=1200)),
        ),
    ]
