# Generated by Django 3.1.3 on 2020-11-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_auto_20201102_1924"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest", models.BooleanField(default=False)),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("hotel", models.CharField(max_length=150)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="accommodation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="events.accommodation",
            ),
        ),
    ]
