# Generated by Django 2.2.7 on 2019-11-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name_plural': 'Families'},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='relationship',
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Family')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.FamilyMember')),
            ],
        ),
    ]
