# Generated by Django 2.1.5 on 2019-12-22 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='family.Family')),
            ],
            options={
                'ordering': ['user__date_joined'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='family.Family'),
        ),
    ]
