# Generated by Django 2.2.7 on 2019-11-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='title',
        ),
    ]
