# Generated by Django 2.2.7 on 2019-11-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20191118_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationType', models.CharField(choices=[(1, 'Parent'), (2, 'Child'), (3, 'Sibilings'), (4, 'Partner')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Person123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonFamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Person123')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.FamilyMember123')),
            ],
        ),
        migrations.AddField(
            model_name='familymember123',
            name='person',
            field=models.ManyToManyField(through='family.PersonFamilyMember', to='family.Person123'),
        ),
    ]
