# Generated by Django 2.2.7 on 2019-11-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_remove_parent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
