# Generated by Django 3.0 on 2019-12-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20191222_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
    ]
