# Generated by Django 2.2.7 on 2019-11-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20191119_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
    ]
