# Generated by Django 2.1.5 on 2019-12-25 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0003_auto_20191225_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='id',
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
