# Generated by Django 2.2.7 on 2019-11-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20191118_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonFamilyMember',
            new_name='PersonFamilyMember123',
        ),
        migrations.AlterField(
            model_name='familymember123',
            name='relationType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Partner'), (2, 'Parent'), (3, 'Child'), (4, 'Sibling')]),
        ),
    ]
