# Generated by Django 2.2.7 on 2019-11-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_remove_child_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['id'], 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['user__date_joined']},
        ),
    ]
