# Generated by Django 3.0 on 2019-12-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20191225_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
