# Generated by Django 3.0.4 on 2020-03-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191226_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_locale',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
