# Generated by Django 2.2.7 on 2019-11-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191114_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Unidentified'), (1, 'Child'), (2, 'Parent'), (3, 'Coach'), (4, 'Admin')], null=True),
        ),
    ]
