# Generated by Django 2.2.7 on 2019-11-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191115_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
