# Generated by Django 3.1.2 on 2020-10-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('family', '0002_child_familymember'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_events.event_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.season'),
        ),
        migrations.AddField(
            model_name='category',
            name='members',
            field=models.ManyToManyField(blank=True, to='family.Child'),
        ),
        migrations.AddField(
            model_name='category',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.season'),
        ),
        migrations.AddField(
            model_name='skirace',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.raceorganizer'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('season', 'name')},
        ),
    ]
