# Generated by Django 3.1.2 on 2020-10-27 20:17

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20201027_2114"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SKI_TRAINING", "Ski Training"),
                            ("ATHLETIC_TRAINING", "Athletic Training"),
                            ("SKI_RACE", "Ski Race"),
                            ("SKI_CAMP", "Ski Camp"),
                            ("VIDEO_ANALYZE", "Video Analyze"),
                            ("MEETING", "Meeting"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FF0000", max_length=18),
                ),
                ("need_skis", models.BooleanField(default=True)),
            ],
        ),
    ]
