# Generated by Django 3.0.5 on 2020-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200428_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skitraining',
            name='extra_field_for_ski_training',
        ),
        migrations.AddField(
            model_name='raceorganizer',
            name='shorthand',
            field=models.CharField(default='SLA', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raceorganizer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skirace',
            name='skis_type',
            field=models.CharField(choices=[('ALL', 'All'), ('SL', 'Slalom'), ('GS', 'Giant Slalom')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='skitraining',
            name='skis_type',
            field=models.CharField(choices=[('ALL', 'All'), ('SL', 'Slalom'), ('GS', 'Giant Slalom')], default='ALL', max_length=3),
        ),
    ]
