# Generated by Django 3.0.5 on 2020-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200515_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceorganizer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
