# Generated by Django 3.1.2 on 2020-11-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_location_need_ski"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventtype",
            old_name="name",
            new_name="type",
        ),
        migrations.AlterUniqueTogether(
            name="eventtype",
            unique_together={("type", "need_skis")},
        ),
    ]
