# Generated by Django 3.1.3 on 2020-11-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201104_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_id',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
    ]
