# Generated by Django 3.1.3 on 2020-11-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_event_group_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="event",
            name="group_id",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
