# Generated by Django 3.0.4 on 2020-03-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200326_2029'),
        ('family', '0003_auto_20200322_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='categories',
            field=models.ManyToManyField(to='events.Category'),
        ),
    ]
