# Generated by Django 3.0.4 on 2020-03-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200326_2036'),
        ('family', '0004_child_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='categories',
            field=models.ManyToManyField(blank=True, to='events.Category'),
        ),
    ]
