# Generated by Django 3.0.4 on 2020-03-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200326_2036'),
        ('family', '0005_auto_20200326_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
