# Generated by Django 3.0.4 on 2020-03-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_child_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='events',
        ),
    ]
