# Generated by Django 3.0.4 on 2020-03-12 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('U_8', 'Superbaby'), ('U_10', 'Mladší predžiaci'), ('U_12', 'Starší predžiaci'), ('U_14', 'Mladší žiaci'), ('U_16', 'Starší žiaci'), ('U_18', 'Juniory'), ('U_21', 'Dospelý')], default='Undefinied', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkiTraining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 3, 12, 22, 13, 41, 496050))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 12, 22, 13, 41, 496050))),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('skis_type', models.CharField(choices=[('GS', 'Giant Slalom'), ('SL', 'Slalom'), ('AL', 'All')], default='AL', max_length=2)),
                ('number_of_turns', models.PositiveSmallIntegerField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkiRace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 3, 12, 22, 13, 41, 496050))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 12, 22, 13, 41, 496050))),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('skis_type', models.CharField(choices=[('GS', 'Giant Slalom'), ('SL', 'Slalom'), ('AL', 'All')], default='AL', max_length=2)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AthleticTraining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 3, 12, 22, 13, 41, 496050))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 12, 22, 13, 41, 496050))),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AthleticCamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 3, 12, 22, 13, 41, 496050))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 12, 22, 13, 41, 496050))),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
