# Generated by Django 3.0.3 on 2020-02-20 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('U_8', 'Superbaby'), ('U_10', 'Mladší predžiaci'), ('U_12', 'Starší predžiaci'), ('U_14', 'Mladší žiaci'), ('U_16', 'Starší žiaci'), ('U_18', 'Juniory'), ('U_21', 'Dospelý')], default='Undefinied', max_length=4),
        ),
        migrations.AddField(
            model_name='season',
            name='year',
            field=models.CharField(default='2018/2019', max_length=9, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SkiTraining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 9, 57, 694343))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 17, 9, 57, 694343))),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('skis_type', models.CharField(choices=[('GS', 'Giant Slalom'), ('SL', 'Slalom'), ('AL', 'All')], default='AL', max_length=2)),
                ('number_of_turns', models.PositiveSmallIntegerField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkiRace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 9, 57, 694343))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 17, 9, 57, 694343))),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('skis_type', models.CharField(choices=[('GS', 'Giant Slalom'), ('SL', 'Slalom'), ('AL', 'All')], default='AL', max_length=2)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AthleticTraining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 9, 57, 694343))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 17, 9, 57, 694343))),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AthleticCamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 9, 57, 694343))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 17, 9, 57, 694343))),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=150)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
