# Generated by Django 3.0.3 on 2020-02-20 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200220_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleticcamp',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 17, 42, 22, 104377)),
        ),
        migrations.AlterField(
            model_name='athleticcamp',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 42, 22, 104377)),
        ),
        migrations.AlterField(
            model_name='athletictraining',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 17, 42, 22, 104377)),
        ),
        migrations.AlterField(
            model_name='athletictraining',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 42, 22, 104377)),
        ),
        migrations.AlterField(
            model_name='skirace',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 17, 42, 22, 104377)),
        ),
        migrations.AlterField(
            model_name='skirace',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 42, 22, 104377)),
        ),
        migrations.AlterField(
            model_name='skitraining',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 20, 17, 42, 22, 104377)),
        ),
        migrations.AlterField(
            model_name='skitraining',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 42, 22, 104377)),
        ),
    ]
