# Generated by Django 3.0.4 on 2020-03-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200329_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('public', 'Public'), ('child', 'Child'), ('parent', 'Parent'), ('coach', 'Coach'), ('editor', 'Editor'), ('admin', 'Admin')], default='public', max_length=6),
        ),
    ]
