# Generated by Django 3.0.4 on 2020-03-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200324_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('public', 'Public'), ('child', 'Child'), ('parent', 'Parent'), ('coach', 'Coach'), ('editor', 'Editor'), ('admin', 'Admin')], default='admin', max_length=6),
            preserve_default=False,
        ),
    ]
