# Generated by Django 3.0.4 on 2020-03-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
