# Generated by Django 3.0.4 on 2020-03-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200329_0026'),
        ('users', '0007_auto_20200324_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
