# Generated by Django 3.0.4 on 2020-03-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200329_0033'),
        ('users', '0008_profile_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='events',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
