# Generated by Django 3.0.4 on 2020-03-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200329_0046'),
        ('users', '0009_auto_20200329_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
