# Generated by Django 3.1.3 on 2020-11-22 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0024_event_all_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_stats.statistic_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.season"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EventStatistic",
            fields=[
                (
                    "statistic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stats.statistic",
                    ),
                ),
                ("add", models.IntegerField(blank=True, default=0, null=True)),
                ("subtract", models.IntegerField(blank=True, default=0, null=True)),
                ("total_add", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "total_subtract",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("stats.statistic",),
        ),
        migrations.CreateModel(
            name="PerformanceTestStatistic",
            fields=[
                (
                    "statistic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stats.statistic",
                    ),
                ),
                ("date", models.DateField()),
                ("long_jump", models.FloatField(blank=True, default=0, null=True)),
                ("high_jump", models.FloatField(blank=True, default=0, null=True)),
                (
                    "twelve_minutes_run",
                    models.DurationField(
                        blank=True,
                        default="00:00",
                        help_text='"MM:SS" format',
                        null=True,
                    ),
                ),
                (
                    "boating",
                    models.DurationField(
                        blank=True,
                        default="00:00",
                        help_text='"MM:SS" format',
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("stats.statistic",),
        ),
        migrations.CreateModel(
            name="RaceStatistic",
            fields=[
                (
                    "statistic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stats.statistic",
                    ),
                ),
                ("date", models.DateField()),
                ("position", models.IntegerField(blank=True, default=0, null=True)),
                ("diff_to_first", models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("stats.statistic",),
        ),
    ]
