name: Build & test

on:
  push:
    branches-ignore:
      - master
      - develop

  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build prod version
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Flake8
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml  run --rm backend flake8 --exit-zero  --statistics

      - name: Test
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml  run --rm backend python manage.py test
