name: Build & test

on:
  push:
    branches-ignore:
      - master

    # Publish `v1.2.3` tags as releases.
    tags-ignore:
      - !v*

  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build & up prod version
        run: docker-compose -f docker-compose-ci.yml up --build

      - name: Show docker processes
        run: docker ps

      - name: Show docker images
        run: docker images

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Flake8
        run: docker-compose run --rm backend flake8 --exit-zero  --statistics

      - name: Test
        run: docker-compose run --rm backend python manage.py test
