name: Sport Club Management System via Docker

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the services in the docker-compose.yml file
    - uses: actions/checkout@v2
      run: docker-compose up --build

    - name: Flake8
      run: docker-compose run backend flake8 --exit-zero  --statistics

    - name: Test
      run: docker-compose run --rm backend python manage.py test
