name: Sport Club Management System

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Lint with flake8
        run: |
          pipenv run flake8 . --count --exit-zero --statistics
      - name: Test
        run: |
          pipenv run python app/manage.py test
