name: Build & Test

on:
  push:
  pull_request:

env:
  ENVIRONMENT: develop
  BACKEND_IMAGE_NAME: backend
  NGINX_IMAGE_NAME: nginx


jobs:
  create-envfile:
    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "123456abcdef"
          file_name: .env
          fail_on_empty: true

      - name: Check env file in another job
        run: cat .env

  build-backend:
    runs-on: ubuntu-latest
    needs: [ create-envfile ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build backend image
        run: docker build ./backend --file backend/Dockerfile

      - name: Check env file in another job
        run: cat .env

  build-nginx:
    runs-on: ubuntu-latest
    needs: [ create-envfile ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build backend image
        run: docker build ./backend --file backend/Dockerfile

  lint:
    runs-on: ubuntu-latest
    needs: [ build-backend ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: flake8 --all-files

      - name: Check migrations
        run: docker-compose run --rm backend poetry run python manage.py makemigrations --dry-run --check || (echo 'Error in migrations dry-check' && exit 1)

  test:
    runs-on: ubuntu-latest
    needs: [ build-backend ]

    steps:
      - name: Run tests
        run: echo "Running tests on $IMAGE"

  push-backend-to-container-repository:
    name: Push backend Docker image to container repository
    needs: [ test, lint, build-nginx ]
    runs-on: ubuntu-latest

    steps:
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: echo "Push $IMAGE image to GitHub Container Registry"

  push-nginx-to-container-repository:
    name: Push backend Docker image to container repository
    needs: [ test, lint, build-nginx ]
    runs-on: ubuntu-latest

    steps:
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: echo "Push $IMAGE image to GitHub Container Registry"

  deploy:
    name: Deploy
    needs: [ push-backend-to-container-repository, push-nginx-to-container-repository ]
    runs-on: ubuntu-latest

    steps:
      - name: Push to $ENVIRONMENT environment
        run: echo "Push mock"
