name: Publish Docker image

on: [push]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: sportagenda

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build prod version
        run: docker-compose -f docker-compose-ci.yml build

      - name: Show docker cointainers
        run: docker ps

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: sportagenda # Provide Docker image name
          image-tag: head # Provide Docker image tag
