name: Deploy services

on: []
#on:
#  workflow_run:
#    workflows:
#      - Publish packages
#    types:
#      - completed
#    branches:
#      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command to rebuild images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git reset --hard HEAD
            git pull origin develop
            docker-compose -f docker-compose-prod.yml up -d --build --force-recreate --no-deps
